### ISSUE TITLE
Grafana datasource does not provide protocol

### ISSUE THREAD

**Issue by braunsonm** [cloudfoundry/cf-k8s-prometheus#9]
## Describe the bug
Grafana deployment specifies the prometheus datasource incorrectly. The current configuration without the protocol will work for graphing but will cause errors when you setup alerts.

The link to the prometheus datasource should include the protocol (aka prepend `http://`)

## To Reproduce*
1. Deploy this project with Grafana
2. Try to make an alert in Grafana
3. Have it get triggered and view the error stating it is missing the protocol

## Expected behavior
Alerting should work out of the box

## Additional context

To fix this yourself, apply the following overlay:

```yaml
#! A bug in Grafana if you do not specify the protocol scheme alerting will stop
#! working. By default CF does not.
#@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata": {"name": "grafana-datasources"}})
---
data:
  prometheus.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.cf-system.svc.cluster.local
```
